[default_session]
startup_command = "nvim +GoToFile"
startup_command_ignore_dirs = ["$HOME/Projects", "$HOME/.config"]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tmux plugins"
path = "$HOME/.config/tmux/plugins"
startup_command = "sesh connect (ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"

[[session_preview]]
pattern_folder_has = "README.md"
preview_command = "glow -s light {}"

[[session]]
name = "sesh config"
path = "$HOME/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --language=toml --style=snip --color=always $HOME/.config/sesh/sesh.toml"

[[session]]
name = "macmon"
path = "~/"
startup_command = "macmon"

# [[session]]
# name = "update"
# path = "/tmp"
# startup_command = "update"
# preview_command = "bat --language=fish --style=snip --color=always $HOME/.config/bin/update"

[[session]]
name = "aerospace config"
path = "$HOME/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --style='full' --color=always $HOME/.config/aerospace/aerospace.toml"

[[session]]
name = "ghostty config"
path = "$HOME/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "pick worktree"
path = "$HOME/Projects/code/github.com/tackle-io/"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "Home 🏡"
path = "$HOME"
startup_command = "l"

[[session]]
name = "Code 💻"
path = "$HOME/Projects/code/github.com/tackle-io/"
startup_command = "l"

[[session]]
name = "tmux config"
path = "$HOME/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always $HOME/.config/tmux/tmux.conf"
# TODO: add `always_top = true` to force this to always be the top result
# TODO: do the same for ghostty

[[session]]
name = "gitmux config"
path = "$HOME/.config/tmux"
startup_command = "nvim gitmux.conf"

[[session]]
name = "neovim config"
path = "$HOME/.config/nvim"

[[session]]
name = "fish config"
path = "$HOME/.config/fish"
preview_command = "bat --language=fish --style=snip --color=always $HOME/.config/fish/config.fish"

[[session]]
name = "yazi config"
path = "$HOME/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "obsidian"
path = "$HOME/Projects/writing/obsidian-vault"
startup_command = "nvim +ObsidianToday"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"
